CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(60),
    DESCRIPTION VARCHAR(60),
    STOCK_QUANTITY INT,
    UNIT_PRICE DECIMAL(10, 2)
);
CREATE TABLE BASKET (
    ID_BASKET INT PRIMARY KEY,
    OP_DATE date,
    FOREIGN KEY (ID) REFERENCES PRODUCT(ID)
 
);

CREATE TABLE `ORDER` (
    ID_ORDER INT PRIMARY KEY,
    DATE DATE,
    QUANTITY INT,
    FOREIGN KEY (ID_BASKET) REFERENCES BASKET(ID_BASKET)
);
